### ISSUE TITLE
Syntax for Restclient

### ISSUE THREAD

**Issue by binhtddev** [pr4th4m/coc-restclient#11]
Is there any language highlight syntax suggestion for this project. I had to rewrite the syntax and snippet to vim but it was very dirty code. I just ask for something better?
This is my temporary project, thanks: https://github.com/binhtran432k/vim-restclient-syntax

**Comment by pr4th4m** [comment]
Hey @binhtran432k 

If you are using neovim, seems like `NTBBloodbath` has written http grammar for Treesitter
- https://github.com/nvim-treesitter/nvim-treesitter/pull/1978
- https://github.com/NTBBloodbath/tree-sitter-http

Http rest client which uses above grammar
https://github.com/NTBBloodbath/rest.nvim

You can refer this for your `vim-restclient-synatx`
Hope this helps :)
